Decouple backend into RISCV and ARM
jserv/shecc pull request #42
Opened 2021-01-18 06:50 UTC by eecheng87

This patch is prepared for importing RISC-V backend in future.
Config variable in Makefile to switch target machine,
also need to config included backend file in main.c

2021-01-18 07:44 UTC, jserv requested changes
How about adding new target "make config"? It can configure the specific targets. The sample usage would be "make config" (Arm target), "make config ARCH=arm" (explicit Arm target) and "make config ARCH=riscv" (explicit RISC-V target)

2021-01-19 01:55 UTC, eecheng87 commented
I've added new way to switch between modes.

Quick demo:
```shell
Demo:

$ make config ARCH=arm
Target machine code switch to arm

$ make
  CC+LD	out/inliner
  GEN	out/libc.inc
  CC	out/src/main.o
  LD	out/shecc
  SHECC	out/shecc-stage1.elf
  SHECC	out/shecc-stage2.elf
```

If it looks good for you, please tell me. I'll also change README about configuration (maybe in this or next PR)

2021-01-19 05:21 UTC, jserv commented
> If it looks good for you, please tell me. I'll also change README about configuration (maybe in this or next PR)

It looks great. Thanks. Let's work within this pull request.

2021-01-19 05:21 UTC, jserv commented on tests/driver.sh
> +    "$target_exe" "$tmp_exe"
should be `$target_exec`

2021-01-19 06:25 UTC, jserv commented on README.md
> +Target machine code switch to arm
Should be `# Target machine code switch to Arm`

2021-01-19 06:25 UTC, jserv commented on README.md
> +Target machine code switch to riscv
Ditto.

2021-01-19 07:01 UTC, jserv commented on tests/driver.sh
> +    $target_exe "$tmp_exe"
Should be `$target_exec`

2021-01-19 07:01 UTC, jserv commented on src/main.c
> +/* include "riscv-codegen.c" */
Remove `riscv-codegen.c` here.

2021-01-19 07:07 UTC, merged