Enhance function lookup with optimized trie data structure
jserv/shecc pull request #58
Opened 2023-07-11 21:10 UTC by zoo868e

Changes:

- Added a new struct trie_t in defs.h to represent the trie.
- Created functions insert_trie_t and search_trie_t to handle trie operations.

2023-07-12 01:21 UTC, jserv commented on src/defs.h
> +typedef struct trie_t{
Replace `typedef struct trie_t` with `typedef struct` (anonymous structure).

2023-07-12 01:23 UTC, jserv requested changes
Append a newline at the end of src/defs.h and run `clang-format` to ensure the consistent style.

2023-07-12 01:31 UTC, jserv commented
You shall read [CONTRIBUTING.md](https://github.com/jserv/shecc/blob/master/CONTRIBUTING.md) carefully and enforce the preferable style.

2023-07-12 18:40 UTC, jserv commented on src/defs.h
> +typedef struct trie_t {
Rewrite as `typedef struct {`.

2023-07-12 18:44 UTC, zoo868e commented on src/defs.h
> +typedef struct trie_t {
Done

2023-07-12 18:44 UTC, jserv commented on src/globals.c
> +trie_t *FUNCS_TRIE;
Rename to `FUNC_TRIES` to emphasize a collection of trie data structure associated with functions.
In addition, add some comments.

2023-07-12 18:45 UTC, jserv commented on src/globals.c
> +
Avoid unnecessary blank lines.

2023-07-12 18:49 UTC, jserv commented on src/globals.c
> + * Parameters:
Check https://www.kernel.org/doc/html/v4.10/doc-guide/kernel-doc.html for writing [Sphinx](http://www.sphinx-doc.org/) friendly comments.

2023-07-12 18:50 UTC, jserv commented on src/globals.c
> +void insert_trie_t(trie_t *trie, char *name, int funcs_index)
The function name should be `insert_trie`.

2023-07-12 18:50 UTC, jserv commented on src/globals.c
> +int search_trie_t(trie_t *trie, char *name)
Ditto. Rename to `find_trie`.

2023-07-12 18:51 UTC, jserv commented on src/globals.c
> +    else
The `else` statement is unnecessary.

2023-07-12 18:53 UTC, jserv requested changes
Squash git commits and mention the benefits (and some measurements) with the proposed change.

2023-07-12 18:54 UTC, jserv commented on src/defs.h
> +} trie_t;
See https://medium.com/@alexey.inkin/how-to-force-newline-at-end-of-files-and-why-you-should-do-it-fdf76d1d090e

2023-07-14 19:25 UTC, jserv requested changes
Don't check in the generated plots. Instead, summarize in git commit messages.

2023-07-14 20:03 UTC, jserv requested changes
Rebase the latest `master` branch.

2023-07-14 20:31 UTC, jserv commented
> Rebase the latest `master` branch.

@zoo868e, Don't use `git merge`. Use `git rebase` instead.

2023-07-14 20:40 UTC, zoo868e commented
I see, I'll do it again

2023-07-14 21:03 UTC, zoo868e commented
Hi @jserv, I apologize for the inconvenience. I need assistance with the git rebase. In my local repository, I have already rebased the master branch to upstream/master. However, I'm unable to push the changes.

* b536f0e (HEAD -> master, temp) Stop check in results
* 359eff8 CI: Enforce newline at end of files
* 4b9fbf3 Stop check in results
* 94ee595 CI: Enforce newline at end of files
* fd2b64e (upstream/master) Add preliminary contributor guide
| * 4469fa9 (origin/master, origin/HEAD) Stop check in results
| * 70d4ee2 Add preliminary contributor guide
|/
* 7f6a7e7 CI: Enforce newline at end of files

2023-07-14 21:25 UTC, jserv commented
> Hi @jserv, I apologize for the inconvenience. I need assistance with the git rebase. In my local repository, I have already rebased the master branch to upstream/master. However, I'm unable to push the changes.

You can simply expose the changes via `git format-patch` and then rework as new commits.

2023-07-14 21:55 UTC, zoo868e commented
Hi @jserv, it appears that the commits have been squashed. Have I resolved the issue?

2023-07-14 21:56 UTC, jserv requested changes
Do not use markdown syntax in git commit messages. Instead, it is preferable to use plain text.

2023-07-14 21:57 UTC, zoo868e commented
I see, let me fix it

2023-07-15 00:00 UTC, jserv requested changes
Execute `git commit --amend --author=` to change the authorship.
Since you can not resolve the potential SegFault introduced with this patch, you shall append the corresponding FIXME comments.

2023-07-15 11:22 UTC, closed without merging