Support #ifdef...#else...#endif
jserv/shecc pull request #61
Opened 2023-07-22 10:01 UTC by ChinYikMing

#43

2023-07-22 10:26 UTC, jserv requested changes
Append `Close #43` at the end of git commit message.

2023-07-22 10:27 UTC, jserv commented
Check [CONTRIBUTING.md](https://github.com/jserv/shecc/blob/master/CONTRIBUTING.md) to enforce consistent style.

2023-07-22 11:00 UTC, ChinYikMing commented
passed the checks

2023-07-22 11:03 UTC, jserv commented on tests/driver.sh
> +    return x;
The return value is crucial for automated tests. Ensure that 0 is returned in the expected path.

2023-07-22 11:27 UTC, jserv requested changes
The string `Close #43` should appear in the body of git commit message rather than the subject. In addition, read https://cbea.ms/git-commit/ carefully to consolidate the commit message.

2023-07-22 11:29 UTC, jserv commented
I defer to @eecheng87 to validate the proposed changes.

2023-07-23 03:43 UTC, eecheng87 approved these changes

2023-07-23 04:29 UTC, merged

2023-07-23 04:37 UTC, jserv commented
Thank @ChinYikMing for contributing!
You may consider to implement `#if defined(...)` and `#elif`, so that we can refine the existing code such as [lib/c](https://github.com/jserv/shecc/blob/master/lib/c.c). Expected usage:
```c
#if defined(__arm__)
#define __syscall_exit 1
#define __syscall_read 3
#define __syscall_write 4
#define __syscall_close 6
#define __syscall_open 5
#define __syscall_brk 45

#elif defined(__riscv)
#define __syscall_exit 93
#define __syscall_read 63
#define __syscall_write 64
#define __syscall_close 57
#define __syscall_open 1024
#define __syscall_openat 56
#define __syscall_brk 214

#else
#error Unsupported architecture
#endif
```